version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3001:4001"
    depends_on:
      - postgres
    env_file: .env

  evaluation-service:
    build: ./evaluation-service
    container_name: evaluation-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    env_file: .env

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - evaluation-service
    env_file: .env
  
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080" 
    depends_on:
      - auth-service
      - evaluation-service
    restart: unless-stopped
