services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    env_file: .env.db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3001:4001"
    depends_on:
      - postgres
    env_file: .env

  evaluation-service:
    build: ./evaluation-service
    container_name: evaluation-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    env_file: ./evaluation-service/.env
    environment:
    - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - evaluation-service
    env_file: .env
  
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080" 
    depends_on:
      - auth-service
      - evaluation-service
    restart: unless-stopped
  
  mock-schoolday-service:
    build:
      context: ./mock-schoolday-service
    container_name: mock-schoolday-service
    environment:
      - PORT=7001    
      - SD_EXPECTED_CLIENT_ID=dev-client
      - SD_EXPECTED_CLIENT_SECRET=dev-secret
    ports:
      - "7001:7001"  
    restart: unless-stopped

  data-integration-service:
    build:
      context: ./data-integration-service
    container_name: data-integration-service
    environment:
      - PORT=7002
      - DATABASE_URL=postgres://te_user:te_pass_Dev123!@postgres:5432/teacher_eval
      - SD_BASE_URL=http://mock-schoolday-service:7001
      - SD_CLIENT_ID=dev-client
      - SD_CLIENT_SECRET=dev-secret
    depends_on:
      - postgres
      - mock-schoolday-service
    ports:
      - "7002:7002"
    restart: unless-stopped


volumes:
  pgdata: